name: sagemath
channels:
  - conda-forge
  - defaults
dependencies:
  # Core mathematical environment (from install history)
  - python=3.12
  - sage=10.6
  - h5py
  
  # Document generation
  - pandoc  # For markdown to HTML+MathJax conversion
  
  # pip included for potential future project-specific packages

# PDF Generation Requirements:
# Chrome/Chromium must be installed separately on the system for PDF generation
# The workflow is: Markdown → Pandoc → HTML+MathJax → Chrome headless → PDF
#
# Install Chrome/Chromium via system package manager:
# Ubuntu/Debian: sudo apt install google-chrome-stable
# macOS: brew install --cask google-chrome
